plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.3'
}

group = 'net.langdua.iaup'

ext {
    awsSdkVersion = '1.12.797'
    jaxbApiVersion = '2.3.1'
    jaxbRuntimeVersion = '2.3.8'
}

repositories {
    mavenCentral()
    maven {
        name = 'spigotmc'
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
    }
    maven {
        name = 'md-5-snapshots'
        url = 'https://repo.md-5.net/content/repositories/snapshots/'
    }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.20.1-R0.1-SNAPSHOT'
    implementation "com.amazonaws:aws-java-sdk-s3:${awsSdkVersion}"
    runtimeOnly "javax.xml.bind:jaxb-api:${jaxbApiVersion}"
    runtimeOnly "org.glassfish.jaxb:jaxb-runtime:${jaxbRuntimeVersion}"
}

def targetJavaVersion = 8
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.release = targetJavaVersion
    options.encoding = 'UTF-8'
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

shadowJar {
    archiveClassifier.set('')
    mergeServiceFiles()

    relocate 'com.amazonaws', 'net.langdua.iaup_vendor.com.amazonaws'
    relocate 'com.fasterxml.jackson', 'net.langdua.iaup_vendor.com.fasterxml.jackson'
    relocate 'org.apache.commons', 'net.langdua.iaup_vendor.org.apache.commons'
    relocate 'org.joda', 'net.langdua.iaup_vendor.org.joda'
    relocate 'javax.xml.bind', 'net.langdua.iaup_vendor.javax.xml.bind'
    relocate 'javax.activation', 'net.langdua.iaup_vendor.javax.activation'
    relocate 'org.glassfish.jaxb', 'net.langdua.iaup_vendor.org.glassfish.jaxb'
    relocate 'com.sun.xml', 'net.langdua.iaup_vendor.com.sun.xml'
    relocate 'com.sun.istack', 'net.langdua.iaup_vendor.com.sun.istack'
    relocate 'org.jvnet.staxex', 'net.langdua.iaup_vendor.org.jvnet.staxex'
}

jar {
    enabled = false
}

build.dependsOn shadowJar
